### PR TITLE
Support pybind11 2.0 for Debian packaging

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Do not merge!

This only impacts `detail` namespace API.

cc @ghisvail

### CODE REVIEW

**Comment by ghisvail** [comment]
I get the following build error:
```
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:27:0,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/gvaillan/debian/packages/xtensor-python/include/xtensor-python/pycontainer.hpp:27,
                 from /home/gvaillan/debian/packages/xtensor-python/include/xtensor-python/pyarray.hpp:18,
                 from /home/gvaillan/debian/packages/xtensor-python/test/main.cpp:14:
/home/gvaillan/debian/packages/xtensor-python/test/main.cpp: In function ‘int main(int, char**)’:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1532:144: error: return-statement with no value, in function returning ‘int’ [-fpermissive]
 #define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
                                                                                                                                                ^
/home/gvaillan/debian/packages/xtensor-python/test/main.cpp:23:5: note: in expansion of macro ‘import_array’
     import_array()
     ^~~~~~~~~~~~

```

**Comment by SylvainCorlay** [comment]
OK, this seems to be Python 2 specific. PR coming with python 2 CI

**Comment by ghisvail** [comment]
Can I control which Python version gets prioritized? Right now I am doing a local build so both python-numpy and python3-numpy are installed.

**Comment by SylvainCorlay** [comment]
You can set the `-D PYTHON_EXECUTABLE=path/to/python`.

**Comment by ghisvail** [comment]
I confirm the issue is Python 2 specific, I can successfully build and test with #59 + #66 with Python 3.

**Comment by ghisvail** [comment]
Weird, I get a segfault in the test in the Debian builder:
```
[==========] Running 32 tests from 3 test cases.
[----------] Global test environment set-up.
[----------] 14 tests from pyarray
[ RUN      ] pyarray.initializer_constructor
[       OK ] pyarray.initializer_constructor (1 ms)
[ RUN      ] pyarray.shaped_constructor
[       OK ] pyarray.shaped_constructor (0 ms)
[ RUN      ] pyarray.strided_constructor
[       OK ] pyarray.strided_constructor (0 ms)
[ RUN      ] pyarray.valued_constructor
[       OK ] pyarray.valued_constructor (0 ms)
[ RUN      ] pyarray.strided_valued_constructor
[       OK ] pyarray.strided_valued_constructor (0 ms)
[ RUN      ] pyarray.copy_semantic
[       OK ] pyarray.copy_semantic (0 ms)
[ RUN      ] pyarray.move_semantic
[       OK ] pyarray.move_semantic (0 ms)
[ RUN      ] pyarray.reshape
[       OK ] pyarray.reshape (0 ms)
[ RUN      ] pyarray.access
[       OK ] pyarray.access (0 ms)
[ RUN      ] pyarray.indexed_access
[       OK ] pyarray.indexed_access (0 ms)
[ RUN      ] pyarray.broadcast_shape
[       OK ] pyarray.broadcast_shape (0 ms)
[ RUN      ] pyarray.iterator
[       OK ] pyarray.iterator (0 ms)
[ RUN      ] pyarray.initializer_list
[       OK ] pyarray.initializer_list (0 ms)
[ RUN      ] pyarray.zerod
[       OK ] pyarray.zerod (0 ms)
[----------] 14 tests from pyarray (1 ms total)

[----------] 14 tests from pytensor
[ RUN      ] pytensor.initializer_constructor
[       OK ] pytensor.initializer_constructor (0 ms)
[ RUN      ] pytensor.shaped_constructor
[       OK ] pytensor.shaped_constructor (0 ms)
[ RUN      ] pytensor.strided_constructor
[       OK ] pytensor.strided_constructor (0 ms)
[ RUN      ] pytensor.valued_constructor
[       OK ] pytensor.valued_constructor (0 ms)
[ RUN      ] pytensor.strided_valued_constructor
[       OK ] pytensor.strided_valued_constructor (0 ms)
[ RUN      ] pytensor.copy_semantic
[       OK ] pytensor.copy_semantic (0 ms)
[ RUN      ] pytensor.move_semantic
[       OK ] pytensor.move_semantic (0 ms)
[ RUN      ] pytensor.reshape
[       OK ] pytensor.reshape (0 ms)
[ RUN      ] pytensor.transpose
[       OK ] pytensor.transpose (0 ms)
[ RUN      ] pytensor.access
[       OK ] pytensor.access (0 ms)
[ RUN      ] pytensor.indexed_access
[       OK ] pytensor.indexed_access (0 ms)
[ RUN      ] pytensor.broadcast_shape
[       OK ] pytensor.broadcast_shape (0 ms)
[ RUN      ] pytensor.iterator
[       OK ] pytensor.iterator (0 ms)
[ RUN      ] pytensor.zerod
[       OK ] pytensor.zerod (0 ms)
[----------] 14 tests from pytensor (0 ms total)

[----------] 4 tests from pyvectorize
[ RUN      ] pyvectorize.function
[       OK ] pyvectorize.function (0 ms)
[ RUN      ] pyvectorize.lambda
[       OK ] pyvectorize.lambda (0 ms)
[ RUN      ] pyvectorize.complex
Segmentation fault
```

**Comment by SylvainCorlay** [comment]
PR for import_array https://github.com/QuantStack/xtensor-python/pull/67

**Comment by SylvainCorlay** [comment]
To be honest, I am a bit frustrated by the fragility of the numpy C API. The same issue came up in tensorflow and a bunch of other projects apparently.

**Comment by ghisvail** [comment]
It is weird though because it tests fine when I compile and test manually. Could it have something to do with the compile flags injected by Debian during the build?

**Comment by SylvainCorlay** [comment]
We have seen issues with the pybind11 tuples, but not easily reproducible with a simple minimal example.

**Comment by ghisvail** [comment]
Compilation:
```
[ 87%] Building CXX object test/CMakeFiles/test_xtensor_python.dir/test_pyvectorize.cpp.o
[ 87%] Building CXX object test/CMakeFiles/test_xtensor_python.dir/test_pyarray.cpp.o
[ 87%] Building CXX object test/CMakeFiles/test_xtensor_python.dir/test_pytensor.cpp.o
[ 93%] Building CXX object test/CMakeFiles/test_xtensor_python.dir/main.cpp.o
cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test && /usr/bin/c++    -I/<<PKGBUILDDIR>>/include -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.5m -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -march=native -Wunused-parameter -Wextra -Wreorder -Wconversion -std=c++14 -O3 -DNDEBUG   -o CMakeFiles/test_xtensor_python.dir/test_pytensor.cpp.o -c /<<PKGBUILDDIR>>/test/test_pytensor.cpp
cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test && /usr/bin/c++    -I/<<PKGBUILDDIR>>/include -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.5m -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -march=native -Wunused-parameter -Wextra -Wreorder -Wconversion -std=c++14 -O3 -DNDEBUG   -o CMakeFiles/test_xtensor_python.dir/main.cpp.o -c /<<PKGBUILDDIR>>/test/main.cpp
cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test && /usr/bin/c++    -I/<<PKGBUILDDIR>>/include -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.5m -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -march=native -Wunused-parameter -Wextra -Wreorder -Wconversion -std=c++14 -O3 -DNDEBUG   -o CMakeFiles/test_xtensor_python.dir/test_pyarray.cpp.o -c /<<PKGBUILDDIR>>/test/test_pyarray.cpp
cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test && /usr/bin/c++    -I/<<PKGBUILDDIR>>/include -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.5m -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -march=native -Wunused-parameter -Wextra -Wreorder -Wconversion -std=c++14 -O3 -DNDEBUG   -o CMakeFiles/test_xtensor_python.dir/test_pyvectorize.cpp.o -c /<<PKGBUILDDIR>>/test/test_pyvectorize.cpp
/<<PKGBUILDDIR>>/test/main.cpp: In function 'int main(int, char**)':
/<<PKGBUILDDIR>>/test/main.cpp:23:5: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
     import_array()
     ^~~~~~~~~~~~
In file included from /<<PKGBUILDDIR>>/test/test_pyarray.cpp:9:0:
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]':
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include/gtest/gtest.h:1421:23:   required from 'static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]'
/<<PKGBUILDDIR>>/test/test_pyarray.cpp:27:9:   required from here
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include/gtest/gtest.h:1392:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (lhs == rhs) {
       ~~~~^~~~~~
In file included from /<<PKGBUILDDIR>>/test/test_pytensor.cpp:9:0:
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]':
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include/gtest/gtest.h:1421:23:   required from 'static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]'
/<<PKGBUILDDIR>>/test/test_pytensor.cpp:26:9:   required from here
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include/gtest/gtest.h:1392:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (lhs == rhs) {
       ~~~~^~~~~~
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = long int]':
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include/gtest/gtest.h:1421:23:   required from 'static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = long int; bool lhs_is_null_literal = false]'
/<<PKGBUILDDIR>>/test/test_common.hpp:156:9:   required from 'void xt::compare_shape(V&, const R&) [with V = xt::pytensor<int, 3ul>; R = xt::row_major_result<std::array<long int, 3ul> >]'
/<<PKGBUILDDIR>>/test/test_pytensor.cpp:37:33:   required from here
/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test/googletest-src/googletest/include/gtest/gtest.h:1392:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

```

Linkage:
```
[100%] Linking CXX executable test_xtensor_python
cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/test && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_xtensor_python.dir/link.txt --verbose=1
/usr/bin/c++   -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -march=native -Wunused-parameter -Wextra -Wreorder -Wconversion -std=c++14 -O3 -DNDEBUG  -Wl,-z,relro CMakeFiles/test_xtensor_python.dir/main.cpp.o CMakeFiles/test_xtensor_python.dir/test_pyarray.cpp.o CMakeFiles/test_xtensor_python.dir/test_pytensor.cpp.o CMakeFiles/test_xtensor_python.dir/test_pyvectorize.cpp.o  -o test_xtensor_python -rdynamic googletest-build/googlemock/gtest/libgtest_main.a googletest-build/googlemock/gtest/libgtest.a -lpthread -lpython3.5m
```

**Comment by SylvainCorlay** [comment]
Closing since this has been packaged for debian.

**Pull request closed without merging**
