### PR TITLE
Complex

### PR DESCRIPTION
**Pull request by JohanMabille**

### CODE REVIEW

**Comment by nbecker** [comment]
I tried applying the patch for this commit, which applied without complaint.  But:
python3 ./test_numpy_fncs.py
Segmentation fault (core dumped)

**Comment by nbecker** [comment]
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
void pybind11::cpp_function::initialize<pybind11_init()::{lambda(xt::pyarray<std::complex<double> > const&)#1}, pybind11::tuple, xt::pyarray<std::complex<double> > const&, pybind11::name, pybind11::scope, pybind11::sibling>(pybind11_init()::{lambda(xt::pyarray<std::complex<double> > const&)#1}&&, pybind11::tuple (*)(xt::pyarray<std::complex<double> > const&), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) [clone .lto_priv.229] ()
    at /home/nbecker/.local/include/xtensor/xassign.hpp:201
/home/nbecker/.local/include/xtensor/xassign.hpp:201:6251:beg:0x7fffe0c9f39b

**Comment by JohanMabille** [comment]
@nbecker that's really curious, could you tell me which compiler you use, your version of pybind11 and how you build your extension ?

**Comment by nbecker** [comment]
I did:
1. git clone https://github.com/QuantStack/xtensor-python.git xtensor-python-johan

2. git am --signoff 30.patch 
Applying: complex benchmark
Applying: complex arrays fixed

3. pybind11 is a bit of a mix:
Head:     fix-import-error merge
Merge:    dean0x7d/fix-import-error Fix handling of Python exceptions during module initialization
Tag:      v2.0.0 (42)
CI:       None

Unmerged into dean0x7d/fix-import-error (2)
d13f015 fix-import-error merge
2d6bc76 jagerman/array_t-overload-resolution array_t overload resolution support

4. compiled as:
g++ -o numpy_fncs.cpython-35m-x86_64-linux-gnu.os -c -g -std=c++1z -O3 -march=native -fvisibility=hidden -flto -DNDEBUG -ffast-math -fPIC -I/home/nbecker/.local/include -I/usr/include/eigen3 -I/home/nbecker/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m numpy_fncs.cc

**Comment by JohanMabille** [comment]
Ok, the problem seems to happen with `pybind11` >2.0.1 only (current master). However, the test I've added in the PR does not trigger the bug (even with master branch of `pybind11`), the crash occurs after many calls.

Since this PR seems to work fine with `pybind11` 2.0.1, I'll merge it and I'll open a specific issue for this problem.

**Pull request merged**
