### PR TITLE
add support for noconvert

### PR DESCRIPTION
**Pull request by nbecker**

### CODE REVIEW

**Comment by nbecker** [comment]
Should probably add a test, but I'm not familiar with the codebase

**Comment by JohanMabille** [comment]
`xtensor-python` is built with `cmake`:

- the `CMakeLists.txt` file at the root of the project contains, among other things, the lists oth the headers:
```cmake
set(XTENSOR_PYTHON_HEADERS
    ${XTENSOR_PYTHON_INCLUDE_DIR}/xtensor-python/pyarray.hpp
    ${XTENSOR_PYTHON_INCLUDE_DIR}/xtensor-python/pybuffer_adaptor.hpp
    ${XTENSOR_PYTHON_INCLUDE_DIR}/xtensor-python/pycontainer.hpp
    ${XTENSOR_PYTHON_INCLUDE_DIR}/xtensor-python/pytensor.hpp
    ${XTENSOR_PYTHON_INCLUDE_DIR}/xtensor-python/pyvectorize.hpp
    ${XTENSOR_PYTHON_INCLUDE_DIR}/xtensor-python/xtensor_python_config.hpp
)
```

Each time you add a header to the project, you must update this list.

- `test/CMakeLists.txt` contains the instructions to build the pure C++ tests (no python involved). Among them, you have the lists of source files:
```cmake
set(XTENSOR_PYTHON_TESTS
    main.cpp
    test_pyarray.cpp
    test_pytensor.cpp
    test_pyvectorize.cpp
)
```
As for headers, every new cpp test file should be added to this list. Tests rely on `gtest`, having a look at `test/test_pytensor.cpp` should show you how to do your own test.

- `test/test_python` contains the python tests, you can run them with py.test. You can add your C++ code to the `main.cpp` file, and then update `test_pyarray.py` to add python tests.

**Comment by JohanMabille** [comment]
I don't think you need to add the file pytraits.hpp, `numpy_traits` is already provided by `xtensor-python` in the file pycontainer.hpp.

**Comment by nbecker** [comment]
If we add a test for noconvert, we should expect a testcase that will raise an exception.  I didn't see any example of this type of test in the current test directory.

**Comment by nbecker** [comment]
In order to test noconvert, some test case should expect to throw an exception.  I didn't see any example in test dir that shows how to write such a test.  Any hints?

**Comment by JohanMabille** [comment]
Indeed, I think you could rely on numpy.testing.assert_raises; I think pybind11 throws a cast_error when the load method of a `pyobject_caster` fails, but not sure about that.

**Comment by JohanMabille** [comment]
Fixed in #87.

**Pull request closed without merging**
