### PR TITLE
fix casting for int64/uint64 and long long types

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
Some minor fixes in docs. 
needs testing. Comments?

**Comment by wolfv** [comment]
fixes #116

**Comment by JohanMabille** [comment]
Not closing it now so the typo can be merged once #124 is merged.

**Comment by JohanMabille** [comment]
@wolfv do you want to rebase and merge the doc corrections ? So it can be in next release.

**Pull request closed without merging**
